services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - wordpress-files:/var/www/html
    environment:
      SERVICE_URL_WORDPRESS: ${SERVICE_URL_WORDPRESS}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://127.0.0.1
      interval: 2s
      timeout: 10s
      retries: 10

volumes:
  wordpress-files:
